services:
  api:
    container_name: modern_api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-modern_api}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_network
    command: sh -c "npm run db:migrate && npm run dev"
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/
            - dist/

  postgres:
    container_name: modern_api_postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-modern_api}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U ${DB_USER:-postgres}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api_network

  pgadmin:
    container_name: modern_api_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_SERVER_MODE:-False}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_MASTER_PASSWORD_REQUIRED:-False}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_network

volumes:
  postgres_data:
    name: modern_api_postgres_data
  pgadmin_data:
    name: modern_api_pgadmin_data

networks:
  api_network:
    name: modern_api_network
    driver: bridge